version: '3'
services:
  srv_ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    ports:
      - "8080:8080"
    hostname: srvmaster 

  srv_ubuntu_slave_0:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    ports:
      - "8081:8080"
    hostname: srvslave0

  srv_ubuntu_slave_1:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    ports:
      - "8082:8080"
    hostname: srvslave1

  srv_ubuntu_slave_2:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    ports:
      - "8083:8080"
    hostname: srvslav2