version: '3'
services:

  srv_ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    ports:
      - "8080:8080"
    hostname: srvmaster 

  srv_ubuntu_slave:
    build:
      context: .
      dockerfile: Dockerfile.slave
    hostname: srvslave0

  srv_ubuntu_slave_1:
    build:
      context: .
      dockerfile: Dockerfile.slave
    hostname: srvslave1

  srv_ubuntu_slave_2:
    build:
      context: .
      dockerfile: Dockerfile.slave
    hostname: srvslav2