FROM ubuntu:latest

RUN apt update && apt install -y bash python3 nano unzip

RUN apt update && apt install -y openjdk-8-jdk

ENV CONTAINER_NAME=srv_ubuntu
ENV MEMORY_LIMIT=3g

CMD ["/bin/bash", "-c", "while true; do sleep 4600; done"]